### ISSUE TITLE
SE: SVT Play - Some VTT subtitles have guids with hyphens as lines

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1635]
### Describe the bug

Some VTT subtitles have guids with hyphens as lines

## Expected Behavior

No guids in subtitles.

## Actual Behavior

Some VTT subtitles have guids with hyphens as lines

## Pictutes and Possible Fix

<details><summary>Subtitle shows GUID with hyphen</summary>
<p>

#### GUID in subtitles
![before](https://user-images.githubusercontent.com/46671821/166691071-0206c149-11a7-42d7-aa81-54e34e6ad2fa.png)

#### Subtitle srt file.

```

STYLE
::cue {
color: #DFDFDF;
}
::cue(.huvudpratare) {
color: #00FFFF;
}
::cue(.ljud) {
color: #FF00FF;
}
::cue(.ljudskylt) {
color: #FF00FF;
}
::cue(.relivemark) {
color: #FF0000;
}
::cue(.sang) {
color: #00FF00;
}
8ede797e-e9b2-4e3d-a398-8da4beefc575

1
00:00:15,040 --> 00:00:18,680 align:left position:18%
<c.teletext>/KYRKKLOCKOR/</c>
cc277606-fb6c-4942-9089-0451d1ba2f45

2
00:00:42,080 --> 00:00:44,920 align:left position:18%
<c.teletext>Hallå! Du!</c>
f227f058-db3b-45cd-8f57-5497f2cc314d

3
00:00:45,080 --> 00:00:50,480 align:left position:18%
<c.teletext>Snälla. Jag har kört runt i tjugo
minuter för att leta parkeringsplats.</c>
d723a993-cc57-4073-9a9e-6782b5485006

4
00:00:50,640 --> 00:00:55,480 align:left position:18%
<c.teletext>Jag ska på bröllop, sen flyttar jag
bilen. Hör du vad jag säger?</c>
a3d38a2f-c4de-405b-b12b-c60c60b12d5a

```
</p>
</details>

<details><summary>Possible fix</summary>
<p>

File: resources/lib/helpers/subtitlehelper.py

def __convert_web_vtt_to_srt(webvvt):

After (279-280):

            elif Regexer.do_regex("^[0-9a-f]{32}$", line):
                continue

Insert (281-282):

            elif Regexer.do_regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", line):
                continue
</p>
</details>

<details><summary>Subtitle with removed GUID</summary>
<p>

#### No GUID in subtitles
![after](https://user-images.githubusercontent.com/46671821/166691508-17bcb70e-8a2e-41a0-ad95-f72b5ace5bf3.png)

#### Subtitle srt file.

```

STYLE
::cue {
color: #DFDFDF;
}
::cue(.huvudpratare) {
color: #00FFFF;
}
::cue(.ljud) {
color: #FF00FF;
}
::cue(.ljudskylt) {
color: #FF00FF;
}
::cue(.relivemark) {
color: #FF0000;
}
::cue(.sang) {
color: #00FF00;
}

1
00:00:15,040 --> 00:00:18,680 align:left position:18%
<c.teletext>/KYRKKLOCKOR/</c>

2
00:00:42,080 --> 00:00:44,920 align:left position:18%
<c.teletext>Hallå! Du!</c>

3
00:00:45,080 --> 00:00:50,480 align:left position:18%
<c.teletext>Snälla. Jag har kört runt i tjugo
minuter för att leta parkeringsplats.</c>

4
00:00:50,640 --> 00:00:55,480 align:left position:18%
<c.teletext>Jag ska på bröllop, sen flyttar jag
bilen. Hör du vad jag säger?</c>

```
</p>
</details>

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4
- Retrospect version: 5.5.5

**Comment by basrieter** [comment]
See #1625. It was fixed, but not for already downloaded subs. Please clear the Retrospect cache and try again.

**Comment by basrieter** [comment]
Ok, that is an easy fix, I guess.

**Comment by basrieter** [comment]
Can you check: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1635.zip 

(I just updated the code, no time to run it).

**Comment by matsarv** [comment]
I've installed the zip-file. Still showing the GUID in the subtitle.

I used https://regex101.com/ to check the match.

Old GUID - match:
![Image1](https://user-images.githubusercontent.com/46671821/166727312-ddd8873c-b69e-4e55-8707-f951df0b8a02.png)

New GUID with hyphen - no match:
![Image2](https://user-images.githubusercontent.com/46671821/166727374-9425a476-1129-48e7-bd99-66b35a9bed50.png)

**Comment by basrieter** [comment]
Right, I missed something.

**Comment by basrieter** [comment]
Please retry: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1635.zip

**Comment by matsarv** [comment]
Super, now it works for both GUID. Thanks!

**Comment by basrieter** [comment]
Great! I will include it in the next update.
